### ISSUE TITLE
Error with URL Challenge

### ISSUE THREAD

**Issue by hanweic53** [go-lark/lark-gin#3]
I got the error: "Decrypt failed: msg length is less than blocksize" when trying to use LarkChallengeHandler() to handle Message Card Request URL challenge. Does the library currently support Message Card Requests?

**Comment by crispgm** [comment]
I am afraid it does not. Only incoming message request is supported now.

**Comment by hanweic53** [comment]
Ok, thank you for your prompt reply :)
